insert	into category values (1,'Electronics');
insert	into category values (2,'Fashion');
insert	into category values (3,'Home décor');
insert	into category values (4,'Home Maintenance');
insert	into category values (5,'Beauty');
insert	into category values (6,'Personal Care');
insert	into category values (7,'Natural products');
insert	into category values (8,'Healthcare');
insert	into category values (9,'Fitness');
insert	into category values (10,'Pet products');
insert	into category values (11,'Pharmacy');
insert	into category values (12,'HouseHold supplies');
insert	into category values (13,'Sports Supplements');
insert	into category values (14,'Books');
insert	into category values (15,'Furniture');
insert	into category values (16,'Gardens');
insert	into category values (17,'Board Games');
insert	into category values (18,'Bikes');
insert	into category values (19,'Car');
insert	into category values (20,'Radio');
insert	into category values (21,'Skincare');
insert	into category values (22,'Moblie accessories');
insert	into category values (23,'Bike accessories');
insert	into category values (24,'Laptop accessories');
insert	into category values (25,'Camera accessories');
insert	into category values (26,'Baby accessories');
insert	into category values (27,'Men accessories');
insert	into category values (28,'Women accessories');
insert	into category values (29,'Homeware accessories');
insert	into category values (30,'Handmade accessories');
insert	into category values (31,'Jewellery');
insert	into category values (32,'Office Products');
insert	into category values (33,'Industrial products');
insert	into category values (34,'Kitchen products');
insert	into category values (35,'Toys');
insert	into category values (36,'Musical instruments');
insert	into category values (37,'Computer and accessories');
insert	into category values (38,'Video games');
insert	into category values (39,'Subscriptions');
insert	into category values (40,'Frames');
insert	into category values (41,'Cooler');
insert	into category values (42,'AC');
insert	into category values (43,'Mobile');
insert	into category values (44,'Laptops');
insert	into category values (45,'Tables');
insert	into category values (46,'School accessories');
insert	into category values (47,'Camera');
insert	into category values (48,'Men Fashion');
insert	into category values (49,'Women Fashion');
insert	into category values (50,'Audio and Cameras');
