insert	into item values	(1,19000,"Items signed by famous individuals, such as sports jerseys, equipment, musician’s clothing, or musical instruments. Include a certificate of authenticity.","Autographed Memorabilia");	
insert	into item values	(2,1000,"Offer opportunities to meet celebrities like musicians, athletes, comedians, or actors. A lunch or video call with a favorite celebrity can be a unique experience.","Celebrity Meet and Greets");	
insert	into item values	(3,19050,"Auction off tickets to popular concerts, especially special seats like front-row or box seats.","Concert Tickets");	
insert	into item values	(4,29000,"Hard-to-come-by tickets to annual events like the Super Bowl, Coachella, Kentucky Derby, or Sundance Film Festival.","Major Event Tickets");	
insert	into item values	(5,19005,"Beautiful pieces of art, murals, or sculptures that attendees can add to their collections or display in their homes.","Artwork");	
insert	into item values	(6,19005,"High-quality jewelry items like necklaces, bracelets, or rings.","Exquisite Jewelry");	
insert	into item values	(7,69000,"All-inclusive trips to exotic destinations, complete with flights, accommodations, and activities.","Luxury Travel Packages");	
insert	into item values	(8,45464,"Rare and valuable bottles for wine or whiskey enthusiasts.","Fine Wine or Whiskey Collections");	
insert	into item values	(9,155456,"A personal chef prepares a gourmet meal for the winning bidder and their guests.","Private Chef Experience");	
insert	into item values	(10,47989,"A unique adventure for those seeking breathtaking views.","Hot Air Balloon Ride");	
insert	into item values	(11,4648,"An artist creates a beautiful portrait of the winner’s beloved pet.","Custom Pet Portrait");	
insert	into item values	(12,3894,"Tickets to exclusive sports events, locker room tours, or meet-and-greets with athletes.","VIP Sports Experiences");	
insert	into item values	(13,9999000,"A pampering day at a high-end spa with massages, facials, and relaxation.","Luxury Spa Day");	
insert	into item values	(14,57643,"A sommelier guides the winner through a private wine tasting experience.","Private Wine Tasting");	
insert	into item values	(15,523560,"A thrilling aerial tour of the city or scenic landscapes.","Helicopter Tour");	
insert	into item values	(16,67203,"A renowned chef teaches the winner how to prepare a gourmet meal.","Gourmet Cooking Class");	
insert	into item values	(17,6441760,"A unique piece of furniture crafted by a skilled artisan.","Custom-Made Furniture");	
insert	into item values	(18,39645,"A cozy cabin or beach house rental for a relaxing weekend escape.","Weekend Getaway");	
insert	into item values	(19,63580,"A chauffeur-driven ride in a classic car.","Vintage Car Ride");	
insert	into item values	(20,604840,"Bungee jumping, skydiving, or white-water rafting experiences.","Adventure Package");	
insert	into item values	(21,6259070,"A personalized yoga class with a certified instructor.","Private Yoga Session");	
insert	into item values	(22,983866,"Designer handbags from top brands.","Luxury Handbags");	
insert	into item values	(23,7981167,"A golf weekend at a prestigious course.","Golf Getaway");	
insert	into item values	(24,36260,"High-end kitchen gadgets like espresso machines or sous-vide cookers.","Cooking Appliances");	
insert	into item values	(25,564760,"A fashion expert helps the winner revamp their wardrobe.","Personal Styling Session");	
insert	into item values	(26,505456,"A jeweler designs a one-of-a-kind piece based on the winner’s preferences.","Custom-Made Jewelry");	
insert	into item values	(27,6873860,"Dinner at an exclusive restaurant with a private chef.","Fine Dining Experience");	
insert	into item values	(28,99000,"A selection of rare cheeses paired with fine wines.","Artisanal Cheese and Wine Pairing");	
insert	into item values	(29,48084,"A musician performs an intimate concert for the winner and their guests.","Private Concert");	
insert	into item values	(30,59000,"A high-quality timepiece from a renowned brand.","Luxury Watch");	
insert	into item values	(31,69000,"A day on a private yacht or sailboat.","Sailing Adventure");	
insert	into item values	(32,899000,"High-end audio and visual equipment for a home theater.","Home Theater System");	
insert	into item values	(33,499000,"An artist creates a personalized portrait of the winner.","Custom Portrait Painting");	
insert	into item values	(34,525530,"Access to runway shows and exclusive events.","Fashion Week Tickets");	
insert	into item values	(35,7538515,"A collection of aged wines.","Vintage Wine Cellar");	
insert	into item values	(36,5999000,"Learn salsa, tango, or ballroom dancing from a professional.","Private Dance Lesson");	
insert	into item values	(37,8999000,"Scarves, sunglasses, or belts from luxury brands.","Exclusive Fashion Accessories");	
insert	into item values	(38,7999000,"A curated selection of fine foods, chocolates, and delicacies.","Gourmet Food Basket");	
insert	into item values	(39,577910,"A custom star map depicting a significant date and location.","Personalized Star Map");	
insert	into item values	(40,135954,"A short flight on a private jet.","Private Jet Experience");	
insert	into item values	(41,74222,"Pamper yourself at home.","Luxury Spa Robes and Slippers");	
insert	into item values	(42,154555,"A shoemaker designs bespoke shoes.","Custom-Made Shoes");	
insert	into item values	(43,154555,"An expert assesses and organizes the winner’s wine collection.","Wine Cellar Consultation");	
insert	into item values	(44,154555,"Explore a gallery with an art curator.","Private Art Gallery Tour");	
insert	into item values	(45,154555,"Unique pieces with historical value.","Antique Furniture");	
insert	into item values	(46,154555,"High-end kitchen gadgets like espresso machines or sous-vide cookers.","Cooking Appliances");	
insert	into item values	(47,154555,"A fashion expert helps the winner revamp their wardrobe.","Personal Styling Session");	
insert	into item values	(48,154555,"A selection of rare cheeses paired with fine wines.","Artisanal Cheese and Wine Pairing");	
insert	into item values	(49,154555,"A musician performs an intimate concert.","	Private Concert");	
insert	into item values	(50,154555,"All kinds of genres.","Books");	