insert	into notification values (1,'ordered','sms',1);
insert	into notification values (2,'delivered','sms',2);
insert	into notification values (3,'ordered','sms',3);
insert	into notification values (4,'out for delivery','phone',4);
insert	into notification values (5,'out for delivery','phone',5);
insert	into notification values (6,'shipped','sms',6);
insert	into notification values (7,'delivered','sms',7);
insert	into notification values (8,'ordered','sms',8);
insert	into notification values (9,'out for delivery','phone',9);
insert	into notification values (10,'ordered','sms',10);
insert	into notification values (11,'ordered','sms',11);
insert	into notification values (12,'out for delivery','phone',12);
insert	into notification values (13,'ordered','sms',13);
insert	into notification values (14,'out for delivery','phone',14);
insert	into notification values (15,'ordered','sms',15);
insert	into notification values (16,'delivered','sms',16);
insert	into notification values (17,'shipped','sms',17);
insert	into notification values (18,'ordered','sms',18);
insert	into notification values (19,'out for delivery','phone',19);
insert	into notification values (20,'out for delivery','phone',20);
insert	into notification values (21,'ordered','sms',21);
insert	into notification values (22,'delivered','sms',22);
insert	into notification values (23,'delivered','sms',23);
insert	into notification values (24,'shipped','sms',24);
insert	into notification values (25,'ordered','sms',25);
insert	into notification values (26,'ordered','sms',26);
insert	into notification values (27,'out for delivery','phone',27);
insert	into notification values (28,'out for delivery','phone',28);
insert	into notification values (29,'shipped','sms',29);
insert	into notification values (30,'ordered','sms',30);
insert	into notification values (31,'ordered','sms',31);
insert	into notification values (32,'delivered','sms',32);
insert	into notification values (33,'delivered','sms',33);
insert	into notification values (34,'ordered','sms',34);
insert	into notification values (35,'ordered','sms',35);
insert	into notification values (36,'out for delivery','phone',36);
insert	into notification values (37,'shipped','sms',37);
insert	into notification values (38,'out for delivery','phone',38);
insert	into notification values (39,'ordered','sms',39);
insert	into notification values (40,'out for delivery','phone',40);
insert	into notification values (41,'ordered','sms',41);
insert	into notification values (42,'shipped','sms',42);
insert	into notification values (43,'ordered','sms',43);
insert	into notification values (44,'shipped','sms',44);
insert	into notification values (45,'delivered','sms',45);
insert	into notification values (46,'delivered','sms',46);
insert	into notification values (47,'delivered','sms',47);
insert	into notification values (48,'ordered','sms',48);
insert	into notification values (49,'ordered','sms',49);
insert	into notification values (50,'out for delivery','phone',50);
