insert	into shipping values	(1,1,1,0,'A-3, Hariyali Indl Estate, L B S Marg, Behind Shivkrupa Industrial Estate, Vikhroli(w)');
insert	into shipping values	(2,2,2,1,'14, Chandresh Archade, Naya Nagar, Mira Road');
insert	into shipping values	(3,3,3,0,'13, Praslata, Service Road, Khar Nagar, Nr.p R Office, Bandra (w)');
insert	into shipping values	(4,4,4,0, 'Plot No 747, Udyog Vihar, Gurgaon, Gurgaon');
insert	into shipping values	(5,5,5,1,' 3-6-293,1 Floor, Old Mla Qtrs Road,Hyderabad');
insert	into shipping values	(6,6,6,1,' Shop No 2, Kailash Commercial Complex, Lbs Marg, Vikhroli (w)');
insert	into shipping values	(7,7,7,1,'Nr Soni Ni Chawl N.h.no.8, Odhav,Ahmedabad,Gujarat');
insert	into shipping values	(8,8,8,1,'16a, 134, Diamond Bldg, Vithaldas Road, Lohar Chawl');
insert	into shipping values	(9,9,9,0,'18, 18lbrdblr-27, Lb Road,Bangalore');
insert	into shipping values	(10,10,10,0,'S.no.154/2. P.no.48, Maji Sainik Nagar, Yerawada');
insert	into shipping values	(11,11,11,0,'43 Vasai Municipal Indl Estate, Umela Phata, Papadi, Papdi');
insert	into shipping values	(12,12,12,1,'27,Kohinoor Industries, Western Express Highway Rd, Goregaon (e)');
insert	into shipping values	(13,13,13,1,'Shop. No. 5, Mitesh Appt., S V Rd, Opp Sapna Hotel, Malad(w)');
insert	into shipping values	(14,14,14,1,' 23/1, Ground, Nayandahally, Pantharapalya');
insert	into shipping values	(15,15,15,1,' 91-a, 153 Meznanine Flr, Tavawalla Building, Nr Bse Under Taking, Lohar Chawl');
insert	into shipping values	(16,16,16,1,'2/26, Gunbow Street, Opp Khadi Bhandar, Fort');
insert	into shipping values	(17,17,17,1,' 5, Broadway,Chennai');
insert	into shipping values	(18,18,18,0,'29, Mama Parmanand Road, Opera House');
insert	into shipping values	(19,19,19,0,'Gp 14, Hsidc Indl Estate, Gurgaon, Gurgaon');
insert	into shipping values	(20,20,20,0,'13, Nadiadwala Market, Poddar Rd, Malad (east)');
insert	into shipping values	(21,21,21,0,'Shop No 1000, Indira Market, Rd No 25, Opp Sion Post Office, Sion');
insert	into shipping values	(22,22,22,0,'Sahajivan Niwas No 1, Kokan Nagar, Bhandup(w)');
insert	into shipping values	(23,23,23,0,' 214, Blue Chip Complex, Bh Manubhai Tower');
insert	into shipping values	(24,24,24,0,'306 Jagruti Industrial Estate, 367 Pandit Satavalekar Marg, Mogul Lane, Mahim');
insert	into shipping values	(25,25,25,0,' 1a-704, Shree Balaji Nagar, Tirupati Darshan, Station Rd, Behind Union Bank, Bhayander (west)');
insert	into shipping values	(26,26,26,0,'9, Akash Ganga Bldg, Jain Temple Road, Bhayander(w)');
insert	into shipping values	(27,27,27,1,' 16, S;petblr-53, Ds Lane, Chickpet');
insert	into shipping values	(28,28,28,0,'1, Sukhada Building, Opp.garodia Palace , Pant Nagar, Ghatkoper (east)');
insert	into shipping values	(29,29,29,1,'A 34, Part 4 Amar Colony,Delhi');
insert	into shipping values	(30,30,30,1,' 35richmondroad,tatelanebangalore-25, Richmond Road');
insert	into shipping values	(31,31,33,1,'234 Anandraj Indl Est, Sonapur Lane, Bhandup');
insert	into shipping values	(32,32,32,1,'21, 327, Sagar, Narshi Natha Street, Masjid Bunder (east)');
insert	into shipping values	(33,1,1,0,'Al Ameen Towers 69, Wilson Garden');
insert	into shipping values	(34,34,34,0,'Main Market, Old Faridabad, Faridabad, Faridabad');
insert	into shipping values	(35,35,35,0,27, 'Hareram Harekrishna Indl. Esta I.b.patel Rd, Goregaon (east)');
insert	into shipping values	(36,36,36,1,' 14b, Maharaja Nanda Kumar Road, Sarat Bose Road');
insert	into shipping values	(37,37,37,1,'4, Blue Heaven, Sector 5., Airoli, Navi Mumbai');
insert	into shipping values	(38,38,38,1,'3d 3rd Floor Mansoor Ali Mansion, 2nd, Girgaum');
insert	into shipping values	(39,39,39,1,'5,3rd Cross, Msr Industrial Estate, Mathikere');
insert	into shipping values	(40,40,40,1,'Shop 34, Janta Market, Jhandewalan');
insert	into shipping values	(41,41,41,1,'Al Ameen Towers 69, Wilson Garden');
insert	into shipping values	(42,42,42,0,' 14b, Maharaja Nanda Kumar Road, Sarat Bose Road');
insert	into shipping values	(43,43,43,0,'Shop 34, Janta Market, Jhandewalan');
insert	into shipping values	(44,44,44,0,'306 Jagruti Industrial Estate, 367 Pandit Satavalekar Marg, Mogul Lane, Mahim');
insert	into shipping values	(45,45,45,0,'A-3, Hariyali Indl Estate, L B S Marg, Behind Shivkrupa Industrial Estate, Vikhroli(w)');
insert	into shipping values	(46,46,46,0,'Sahajivan Niwas No 1, Kokan Nagar, Bhandup(w)');
insert	into shipping values	(47,47,47,1,'Shop 34, Janta Market, Jhandewalan');
insert	into shipping values	(48,48,48,1,'A 34, Part 4 Amar Colony,Delhi');
insert	into shipping values	(49,49,49,1,' 214, Blue Chip Complex, Bh Manubhai Tower');
insert	into shipping values	(50,50,50,0,'A 34, Part 4 Amar Colony,Delhi');

